# Generated by Django 6.1.2 on 2026-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
